# Generated by Django 4.2.13 on 2024-05-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppListado', '0003_remove_user_bio_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
