# Generated by Django 4.2.13 on 2024-05-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppListado', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
