# Generated by Django 4.2.13 on 2024-05-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppListado', '0006_remove_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='user',
            table='LxL4bMkc3EYQfTw3_users',
        ),
    ]
