# Generated by Django 4.2.13 on 2024-05-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppListado', '0007_alter_user_bio_alter_user_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
