# Generated by Django 4.2.13 on 2024-05-13 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppListado', '0010_authuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
