# Generated by Django 4.2.13 on 2024-05-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppListado', '0012_users_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('departamento', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('juzgado', models.CharField(max_length=100)),
                ('numero_proceso', models.CharField(max_length=25)),
                ('avaluo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_subasta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tipo_bien', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('placa_vehiculo', models.CharField(blank=True, max_length=25, null=True)),
                ('matricula_inmobiliaria', models.CharField(blank=True, max_length=25, null=True)),
                ('referencia_catastral', models.CharField(blank=True, max_length=25, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('referencia', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
